# Site settings
title: ㅁㅍㅋㅋ
subtitle: Mapo Femi Coding Club
email: mfcodingclub@gmail.com
description: We are feminists/developers/digital nomads living in Seoul
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mfcodingclub.github.io/" # the base hostname & protocol for your site
author:
street_address:
city:
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

sass:
  style: compressed
